name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Required for GitHub Pages deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint and Fix (Optional)
        run: yarn lint --fix || true  # Ignore lint errors

      - name: Build and Export Next.js
        run: |
          yarn build
          yarn export

      - name: Setup GitHub Pages
        run: |
          touch out/.nojekyll  # Prevent GitHub from ignoring _next folder
          echo "yourcustomdomain.com" > out/CNAME || true  # Optional custom domain

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to GitHub Pages branch
          folder: out  # Deploy the exported Next.js static files
          clean: true  # Remove old files
